Store/StoreApp/Models/Product.cs
namespace StoreApp.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string? Name { get; set; } = String.Empty;
        public decimal Price { get; set; }
    }
}

Store/StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.DTOs.Product;
using Entities.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public async Task<IActionResult> Index()
        {
            var products = await _manager.ProductService.GetAllProductsWithCategory(false);
            return View(products);
        }

        #region Create Product
        public async Task<IActionResult> Create()
        {
           ViewBag.Categories = new SelectList(await _manager.CategoryService.GetAllCategories(false), nameof(Category.Id), nameof(Category.Name), "1");
           return View();
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion product, IFormFile file) 
        {
            if(ModelState.IsValid)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
                //File Operations
                if (file is not null)
                {
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                        product.ImageUrl = String.Concat("/images/", file.FileName);
                    }         
                }
                await _manager.ProductService.CreateProduct(product);
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }
        #endregion

        #region Update Product
        public async Task<IActionResult> Update(int id)
        {
            ViewBag.Categories = new SelectList(await _manager.CategoryService.GetAllCategories(false), nameof(Category.Id), nameof(Category.Name), "1");
            return View(await _manager.ProductService.GetOneProductForUpdateAsync(id,false));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate product, IFormFile file)
        { 
            if (file is not null)
            {
                string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", file.FileName);
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                    product.ImageUrl = String.Concat("/images/", file.FileName);
                }
            }

            await _manager.ProductService.UpdateProduct(product);
            return RedirectToAction(nameof(Index));
          
        }
        #endregion

        #region Delete Product
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            await _manager.ProductService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        #endregion

    }
}

Store/StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager serviceManager;

        public CategoriesMenuViewComponent(IServiceManager serviceManager)
        {
            this.serviceManager = serviceManager;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await serviceManager.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

Store/StoreApp/Components/ProductFilterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Components
{
    public class ProductFilterMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Store/StoreApp/Controllers/ProductController.cs
using Entities.RequestParameters;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;
using StoreApp.Models;

namespace StoreApp.Controllers
{

    public class ProductController : Controller
    {
        private readonly IServiceManager serviceManager;
        public ProductController(IServiceManager manager)
        {
            serviceManager = manager;
        }

        public async Task<IActionResult> Index(ProductRequestParameters parameters)
        {
            var products = serviceManager.ProductService.GetProductsWithDetails(parameters);
            var count = await serviceManager.ProductService.GetProductCount();
            var pagination = new Pagination()
            {
                CurrentPage = parameters.PageNumber,
                ItemsPerPage = parameters.PageSize,
                TotalItems = count
            };
            return View(new ProductListViewModel()
            {
                Products = products,
                Pagination = pagination
            });
        }
        public async Task<IActionResult> Get([FromRoute(Name ="id")] int id)
        {
            var product = await serviceManager.ProductService.GetOneProduct(id, false);
            return View(product);
        }

    }
}

Store/StoreApp/Views/Product/Get.cshtml
@model Product

<div class="row">
    <div class="col-md 12">
        <div class="text-center">
            <h6 class="display-6">
                @Model.Name
            </h6>

            <img class="img-fluid shadow rounded-3 my-3" width="600" height="600" src="@Model?.ImageUrl" alt="@Model.Name" />

            <p class="lead text-danger">@Model.Price.ToString("c")</p>

            <div class="btn-group">
                <a class="btn btn-primary" asp-controller="Home" asp-action="Index">
                    <i class="fa-solid fa-house"></i>
                    Home
                </a>

                <form id="@Model.Id" asp-page="/cart" method="post">
                    <input type="hidden" asp-for="Id" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <button type="submit" class="btn btn-outline-primary mx-2">
                        <i class="fa-solid fa-cart-shopping"></i>
                        Add to Cart
                    </button>
                </form>


                <a class="btn btn-outline-primary" asp-controller="Product" asp-action="Index">
                    <i class="fa-solid fa-list"></i>
                    Products
                </a>
               
            </div>


        </div>


    </div>
</div>

Store/StoreApp/Views/Product/Index.cshtml
@using StoreApp.Models
@model ProductListViewModel

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
        @await Component.InvokeAsync("ProductFilterMenu")
    </div>

    <div class="col-md-9">
        <div class="row my-3">
            @foreach (var product in Model.Products)
            {
                <partial name="_ProductCard" model="product" />
            }
        </div>
        <div page-model="@Model?.Pagination"
             page-action="Index"
             page-classes-enabled="true"
             page-class="btn"
             page-class-normal="btn-outline-dark"
             page-class-selected="btn-primary"
             class="btn-group"></div>
    </div>
</div>