Store/StoreApp/Controllers/OrderController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class OrderController : Controller
    {
        private readonly IServiceManager _manager;
        private readonly Cart _cart;

        public OrderController(IServiceManager _manager, Cart cart)
        {
            this._manager = _manager;
            _cart = cart;
        }
        public ViewResult Checkout() => View(new Order());

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout([FromForm]Order order)
        {
            if(_cart.Lines.Count == 0)
                ModelState.AddModelError("", "Sorry, your cart is empty!");

            if(ModelState.IsValid)
            {
                order.Lines = _cart.Lines.ToArray();
                await _manager.OrderService.SaveOrder(order);
                _cart.Clear();
                return RedirectToPage("/Complete", new {OrderId = order.OrderId});
            }
            else
                return View(order);    
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Services.Contracts;
using StoreApp.Infrastructure.Extensions;

namespace StoreApp.Pages
{
    public class CartModel : PageModel
    {
        private readonly IServiceManager serviceManager;
        public string ReturnUrl { get; set; } = "/";
        public Cart Cart { get; set; }

        public CartModel(IServiceManager serviceManager, Cart cartService)
        {
            this.serviceManager = serviceManager;
            Cart = cartService;
        }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public async Task<IActionResult> OnPost(int id, string returnUrl)
        {
            Product? product = await serviceManager.ProductService.GetOneProduct(id,false);
            if (product is not null)
            {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new {returnUrl=returnUrl}); // returnUrl
        }

        public IActionResult OnPostRemove(int id, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl => cl.Product.Id == id).Product);
            return Page();
        }
    }
}

Store/StoreApp/Pages/Complete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StoreApp.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Store/StoreApp/Pages/Cart.cshtml
@page "/cart"
@model CartModel

<div>
    <div class="text-center display-6">
        Cart
    </div>
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price</th>
                <th>Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var line in Model.Cart?.Lines ?? Enumerable.Empty<CartLine>())
            {
                <tr>
                    <td>@line.Product.Name</td>
                    <td>@line.Quantity</td>
                    <td>@line.Product.Price.ToString("c")</td>
                    <td>@((line.Product.Price * line.Quantity).ToString("c2"))</td>
                    <td>
                        <form method="post" asp-page-handler="Remove">
                            <input type="hidden" name="id" value="@line.Product.Id" />
                            <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                            <button type="submit" class="btn btn-sm btn-danger">
                                <i class="fa fa-trash"></i>
                                Remove
                            </button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="4" class="text-right">Total : </td>
                <td class="text-right text-danger">
                    @Model.Cart?.ComputeTotalValue().ToString("C2")
                </td>
            </tr>
        </tfoot>
    </table>
    <div class="text-center my-3">
        <div class="btn-group">
            <a class="btn btn-primary" href="@Model?.ReturnUrl">Continue Shopping</a>
            <a class="btn btn-success mx-2" asp-action="Checkout" asp-controller="Order">Checkout</a>
        </div>
    </div>
</div>

Store/StoreApp/Pages/Complete.cshtml
@page
    

<div class="text-center">
    <h6 class="display-6">Thanks</h6>
    <p>Your order is on its way!</p>
    <p>Order ID: #@OrderId</p>
    <a class="btn btn-primary" asp-action="Index" asp-controller="Home">Return To Store</a>
</div>

@functions
{
    [BindProperty(SupportsGet = true)]
    public int OrderId { get; set; }
}

Store/StoreApp/Pages/Contact.cshtml
@page "/getintouch"

<div class="text-center my-5 ">
    <div class="display-6 border-bottom">Contact</div>
    <div class="lead mt-5">
        <i class="fa fa-phone bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            BTK
        </p>
        <i class="fa-solid fa-address-book bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            ADDRESS
        </p>

        <i class="fa-solid fa-envelope bg-secondary text-white p-3  rounded-5 my-3"></i>
        <p>
            SUPPORT
        </p>
    </div>
</div>